# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nugoncal <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/06/13 16:13:52 by nugoncal          #+#    #+#              #
#    Updated: 2025/06/13 16:19:56 by nugoncal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


# Compiler
CC = cc
CFLAGS = -Wall -Wextra - Werror

# Commands
AR = ar -rcs
RM = rm -fr

all: $(NAME)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $()

re:	fclean all
